export const resources = {
  en: {
    translation: {
      nav: { discover: "Discover", movies: "Movies", series: "Series", stats: "Stats", profile: "Profile" },
      common: {
        movie: "Movie",
        movies: "Movies",
        series: "Series",
        all: "All",
        male: "Male",
        female: "Female",
        watchNow: "Watch Now",
        watchedOn: "Watched on {{date}}",
        readMore: "Read more",
        readLess: "Read less",
        seeAll: "See all",
        retry: "Retry",
        cancel: "Cancel",
        save: "Save",
        update: "Update",
        remove: "Remove",
        confirm: "Confirm",
        goBack: "Go Back",
        edit: "Edit",
        searching: "Searching...",
        loading: "Loading...",
        noImage: "No Image",
        noStill: "No Still",
        noPoster: "TBA",
        soon: "Soon",
        unknown: "Unknown",
        unknownYear: "Unknown year",
        today: "Today",
        yesterday: "Yesterday",
        oneWeekAgo: "1 Week Ago",
        justWatched: "Just watched",
      },
      loaders: {
        syncingData: "Syncing your StreamBox data",
        preparingCinemaRoom: "Preparing your cinema room",
        loadingReels: "Loading reels",
        loadingMovies: "Loading movies",
        loadingSeries: "Loading series",
        loadingMovieDetail: "Loading detail",
        loadingSeriesDetail: "Loading series",
        loadingJourneys: "Loading journeys",
        loadingProfile: "Loading profile...",
      },
      player: {
        didYouKnow: "Did you know?",
      },
      liveOps: {
        gotIt: "Got it",
        learnMore: "Learn more",
        updateEyebrow: "Update ready",
        updateTitle: "A fresher StreamBox is ready",
        updateBody: "We downloaded the latest improvements in the background. Restart now to use them right away, or keep watching and let it apply next time you open the app.",
        updateLater: "Later",
        updateRestartNow: "Restart now",
      },
      startupError: {
        title: "StreamBox needs a quick reset",
        message: "Something failed while opening your library. Retry once, or sign out to clear the saved session and return to the welcome screen.",
      },
      welcome: {
        topTitle: "Welcome to",
        headline: "Stream Movies and Series.",
        headlineAccent: "All in One App.",
        description: "Discover, watch, and track thousands of movies and series with personalized recommendations and detailed insights.",
        cta: "Get Started",
      },
      auth: {
        welcomeBack: "Welcome back",
        createAccount: "Create your account",
        signIn: "Sign In",
        signUp: "Sign Up",
        continueWithGoogle: "Continue with Google",
        orContinueWithGoogle: "or continue with Google",
        createAccountButton: "Create Account",
        name: "Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        yourName: "Your name",
        emailPlaceholder: "you@example.com",
        enterPassword: "Enter password",
        reenterPassword: "Re-enter password",
        forgotPassword: "Forgot password?",
        resetPasswordTitle: "Reset Password",
        resetPasswordDescription: "Enter your email address and we'll send you a 6-digit code to reset your password.",
        sendResetCode: "Send Reset Code",
        rememberPassword: "Remember your password?",
        verifyEmailTitle: "Verify Your Email",
        verifyEmailDescription: "We sent a 6-digit code to",
        verifyContinue: "Verify & Continue",
        didNotReceiveCode: "Didn't receive the code?",
        checkSpamFolder: "Check spam folder",
        setNewPassword: "Set New Password",
        setNewPasswordDescription: "Enter the code sent to {{email}} and create your new password.",
        resetCode: "Reset Code",
        resetCodePlaceholder: "6-digit code",
        newPassword: "New Password",
        newPasswordPlaceholder: "New password",
        confirmNewPassword: "Confirm New Password",
        reenterNewPassword: "Re-enter new password",
        passwordChanged: "Password Changed",
        passwordChangedDescription: "Your password has been successfully updated. You can now sign in with your new password.",
        backToSignIn: "Back to Sign In",
        nameRequired: "Name is required",
        emailRequired: "Email is required",
        invalidEmail: "Enter a valid email address",
        passwordRequired: "Password is required",
        passwordRequirements: "Password doesn't meet requirements",
        passwordsDoNotMatch: "Passwords don't match",
        invalidCredentials: "Invalid email or password",
        somethingWentWrong: "Something went wrong",
        sendResetFailed: "Failed to send reset code",
        enterFullOtp: "Enter the full 6-digit code",
        emailRateLimited: "Too many email requests were sent recently. Wait about a minute and try again.",
        verificationFailed: "Verification failed",
        wrongVerificationCode: "Wrong verification code. Please check and try again.",
        resetFailed: "Reset failed",
        codeExpired: "Code expired. Request a new one.",
        invalidCode: "Invalid code",
        ruleMinLength: "8+ characters",
        ruleLowercase: "Lowercase letter",
        ruleUppercase: "Uppercase letter",
        ruleDigit: "Digit",
        ruleSpecial: "Special character",
      },
      home: { discover: "Discover", trendingMovies: "Trending Movies", trendingSeries: "Trending Series", cinematicJourneys: "Cinematic Journeys" },
      movies: { movieOfDay: "Movie of the Day", noMovieOfDay: "No movie of the day", topNewMovies: "Top New Movies", imdbTop250: "IMDb Top 250" },
      series: { seriesOfDay: "Series of the Day", noSeriesOfDay: "No series of the day", topNewSeries: "Top New Series", imdbTop250Series: "IMDb Top 250 Series" },
      search: {
        placeholder: "Search movies & series...",
        noResultsForQuery: "No results for \"{{query}}\"",
        tryDifferentKeywords: "Try different keywords or check spelling",
        pressEnterForFullResults: "Press enter for full results",
        typeAtLeastTwoChars: "Type at least 2 characters to search",
        filteredResults: "Filtered Results",
        resultsCount_one: "{{count}} result",
        resultsCount_other: "{{count}} results",
        noResultsFound: "No Results Found",
        couldNotFindMatch: "We couldn't find anything matching",
        yourFilters: "your filters",
        suggestionCheckSpelling: "Check spelling or try different keywords",
        suggestionUseShorterTerms: "Use shorter or more general terms",
        suggestionAdjustFilters: "Try adjusting the filters",
        resultsFor: "Results for \"{{query}}\"",
        foundMatchingTitles: "Found {{count}}+ titles matching your search",
      },
      filters: {
        title: "Filters",
        reset: "Reset",
        type: "Type",
        movies: "Movies",
        tvSeries: "TV Series",
        genres: "Genres",
        releaseYear: "Release Year",
        from: "From",
        to: "To",
        minimumRating: "Minimum Rating",
        sortBy: "Sort By",
        mostPopular: "Most Popular",
        highestRated: "Highest Rated",
        newestFirst: "Newest First",
        mostVoted: "Most Voted",
        apply: "Apply Filters",
      },
      discover: {
        loadingCollection: "Loading collection",
        noTitlesFound: "No titles found.",
        loadMore: "Load more",
        unableToLoadList: "Unable to load this list.",
        unableToLoadMoreTitles: "Unable to load more titles.",
      },
      franchise: {
        title: "Cinematic Journeys",
        subtitle: "Watch franchises in the right order",
        emptyTitle: "No Journeys Yet",
        emptyDescription: "Franchise roadmaps will appear here once they are added to the collection.",
        noEntries: "No entries found for this franchise.",
        loadingTimeline: "Loading timeline",
        titleCount_one: "{{count}} title",
        titleCount_other: "{{count}} titles",
        titlesInJourney_one: "{{count}} title in the journey",
        titlesInJourney_other: "{{count}} titles in the journey",
        progressCompleted: "{{watched}} of {{total}} completed",
        progressCompletedSubtitleDone: "You have completed this entire franchise",
        progressCompletedSubtitleHint: "Long press any title to mark as watched",
        nextUp: "Next up:",
        journeyComplete: "Journey Complete",
        endOfTimeline: "End of Timeline",
        completeSagaMessage: "You've experienced all {{count}} titles in this saga. What a ride.",
        epicJourneyMessage: "{{count}} titles. One epic journey. How far will you go?",
        signInToTrackProgress: "Sign in to track your progress",
        markedWatched: "Marked \"{{title}}\" as watched",
        unmarkedWatched: "Removed watched mark from \"{{title}}\"",
        failedToUpdateProgress: "Failed to update progress",
      },
      detail: {
        synopsis: "Synopsis",
        castCrew: "Cast & Crew",
        similarMovies: "Similar Movies",
        similarSeries: "Similar Series",
        seasonsEpisodes: "Seasons & Episodes",
        seasonsCount_one: "{{count}} Season",
        seasonsCount_other: "{{count}} Seasons",
        episodesCount_one: "{{count}} Episode",
        episodesCount_other: "{{count}} Episodes",
        seasonLabel: "Season {{number}}",
        watchEpisode: "Watch S{{season}} E{{episode}}",
        watchedEpisodesProgress: "{{watched}} of {{total}} episodes watched",
        episodeSwipeHint: "Swipe any episode card to the right to mark it as watched.",
        noEpisodesForSeason: "No episodes available for this season.",
        noSynopsisAvailable: "No synopsis available.",
        noDetailDataAvailable: "No detail data available.",
        unknownReleaseDate: "Unknown release date",
        cast: "Cast",
        crew: "Crew",
        lowQualityAvailable: "Low Quality Available",
        watchAnyway: "Watch Anyway",
        chooseWatchedDateDescription: "Choose the date you actually watched this {{mediaLabel}}. StreamBox will use this date in watched activity, grids, and timeline stats.",
        markWatchedWithoutDateDescription: "If you don't remember the exact date, you can still mark this title as watched without adding one.",
        markWatchedWithoutDate: "Mark as watched",
        pickSpecificDate: "Choose a date",
        chosenDate: "Chosen date",
        watchedWithoutDate: "Marked as watched",
        watchedInMonth: "Watched in {{date}}",
        seasonTrackingDescription: "Track each finished season with a month or simply mark it as watched without a date.",
        notWatched: "Not watched",
        monthYearMode: "Month & year",
        noDateMode: "No date",
        selectMonthYear: "Select month & year",
        seasonsMarkedWatched_one: "{{count}} season marked watched",
        seasonsMarkedWatched_other: "{{count}} seasons marked watched",
      },
      actor: {
        loadingProfile: "Loading profile",
        unableToLoadProfile: "Unable to load actor profile.",
        noActorDataAvailable: "No actor data available.",
        biography: "Biography",
        biographyFallback: "Biography data is not available for this actor yet. This profile will be expanded in the next phase.",
        knownFor: "Known For",
      },
      profile: {
        watched: "Watched",
        watchlist: "Watchlist",
        liked: "Liked",
        bioLabel: "Bio",
        locationLabel: "Location",
        birthdayLabel: "Birthday",
        sectionCount: "{{count}} {{label}}",
        noMoviesWatchedYet: "No movies watched yet",
        noSeriesWatchedYet: "No series watched yet",
        noMoviesInWatchlist: "No movies in watchlist",
        noSeriesInWatchlist: "No series in watchlist",
        noMoviesLikedYet: "No movies liked yet",
        noSeriesLikedYet: "No series liked yet",
        filterButton: "Filter",
        filterSheetTitle: "Refine this section",
        filterWatchedDescription: "Sort or narrow your watched titles without leaving the profile page.",
        filterWatchlistDescription: "Shape your watchlist view the way you want to browse it right now.",
        filterLikedDescription: "Focus your liked titles by quality, year, or genre.",
        sortBy: "Sort by",
        sortRecentlyAdded: "Recently added",
        sortHighestRated: "Highest rated",
        sortNewestYear: "Newest year",
        sortTitleAZ: "Title A-Z",
        genreFilterTitle: "Genre",
        allGenres: "All genres",
        noGenreFiltersAvailable: "Genre filters will appear once titles in this section have genre data.",
        resetFilters: "Reset",
        applyFilters: "Apply",
        joinedOn: "Joined {{date}}",
        bornOn: "Born {{date}}",
        editProfile: "Edit profile",
        yourName: "Your name",
        addBio: "Add a bio",
        addLocation: "Add your location",
        searchingLocations: "Searching locations...",
        birthdayPlaceholder: "DD/MM/YYYY",
        permissionNeeded: "Permission needed",
        allowPhotoAccessProfile: "Allow photo library access to set a profile picture.",
        allowPhotoAccessBanner: "Allow photo library access to set a banner image.",
        imageError: "Image error",
        couldNotSaveProfileImage: "StreamBox could not save that profile image.",
        couldNotSaveBannerImage: "StreamBox could not save that banner image.",
      },
      settings: {
        title: "Settings",
        pageEyebrow: "Personal space",
        pageLeadTitle: "Shape StreamBox around the way you watch.",
        pageLeadDescription: "Fine-tune language, look, backups, and feedback from one calm control room.",
        languageTitle: "Language",
        languageDescription: "Choose the app language. English stays the default, and your preference is saved to your account.",
        appThemeTitle: "App Theme",
        appThemeDescription: "Choose the accent that drives tabs, buttons, toggles, loaders, and the global app look.",
        backupTitle: "Backup & Transfer",
        backupDescription: "Export one StreamBox backup file, move it to another phone, then import it to restore your profile, theme, likes, watchlists, and history.",
        dataPortability: "Data Portability",
        exportAllData: "Export all data",
        importBackup: "Import backup",
        preparingBackup: "Preparing backup...",
        importingBackup: "Importing backup...",
        importReplacesData: "Import replaces the current phone data with the selected backup file.",
        backupReady: "backup file is ready to save or send to your new phone",
        backupImported: "backup imported and all saved data has been restored",
        exportFailed: "Export failed",
        backupCreateFailed: "StreamBox could not create a backup file.",
        importFailed: "Import failed",
        backupRestoreFailed: "StreamBox could not restore that backup file.",
        importBackupTitle: "Import backup",
        importBackupMessage: "This will replace the current StreamBox data on this phone with the selected backup.",
        importComplete: "Import complete",
        importCompleteMessage: "Your StreamBox data and settings have been restored on this phone.",
        sharingUnavailable: "Sharing is not available on this device.",
        feedbackTitle: "Feedback",
        feedbackDescription: "If something feels off or you have an idea, send it directly from StreamBox.",
        feedbackLabel: "Your message",
        feedbackPlaceholder: "Tell us what happened, what you expected, or what you would improve...",
        sendFeedback: "Send feedback",
        sendingFeedback: "Sending feedback...",
        feedbackSentTitle: "Feedback sent",
        feedbackSentMessage: "Thanks. Your feedback was sent successfully.",
        feedbackFailedTitle: "Feedback failed",
        feedbackFailedMessage: "StreamBox could not send your feedback right now. Please try again.",
        feedbackTooShortTitle: "More detail needed",
        feedbackTooShortMessage: "Please write at least a short sentence so we can understand the issue.",
        accountTitle: "Account",
        accountDescription: "Sign out of your StreamBox account on this device.",
        signOut: "Sign Out",
        signingOut: "Signing you out...",
        signOutConfirmTitle: "Log out of StreamBox?",
        signOutConfirmMessage: "Are you sure you want to sign out? Your session will be ended.",
        enLabel: "English",
        enDescription: "Default app language.",
        trLabel: "Türkçe",
        trDescription: "Natural Turkish interface.",
        themeCinemaEmberName: "Cinema Ember",
        themeCinemaEmberDescription: "Classic StreamBox heat with a premium cinema glow.",
        themeVelvetCrimsonName: "Netflix Red",
        themeVelvetCrimsonDescription: "Netflix-inspired signature red for a bold but familiar premium streaming look.",
        themeAuroraCyanName: "Prime Video Blue",
        themeAuroraCyanDescription: "Prime Video-inspired blue with a bright streaming accent and familiar dark-mode contrast.",
        themeEmeraldNoirName: "Emerald Noir",
        themeEmeraldNoirDescription: "Dark screen, rich green highlights, understated and premium.",
      },
      stats: {
        emptyState: "Start watching to unlock your stats.",
        recap: "Recap",
        watched: "Watched",
        hours: "Hours",
        episodes: "Episodes",
        avgScore: "Avg score",
        watchActivityTitle: "Watch Activity",
        watchActivitySubtitle: "How often you've been watching week by week.",
        chartTotal: "Total",
        chartPeakWeek: "Peak week",
        chartActive: "Active",
        now: "Now",
        weekShort: "w",
        decadeSpreadTitle: "Decade Spread",
        decadeSpreadSubtitle: "Which eras your picks come from.",
        noDecadeDistribution: "No decade distribution yet.",
        genreBreakdownTitle: "Genre Breakdown",
        genreBreakdownSubtitle: "Your most watched genres ranked by count.",
        noGenrePatterns: "No genre patterns yet.",
        genreRadarTitle: "Genre Radar",
        genreRadarSubtitle: "A visual map of how your top genres compare.",
        dominant: "Dominant",
        share: "Share",
        ratingDistributionTitle: "Rating Distribution",
        ratingDistributionSubtitle: "How your ratings spread across the scale.",
        runtimeExtremesTitle: "Runtime Extremes",
        runtimeExtremesSubtitle: "Your shortest and longest watches side by side.",
        longest: "Longest",
        shortest: "Shortest",
        tasteEvolutionTitle: "Taste Evolution",
        tasteEvolutionSubtitle: "How your genre preferences shift month to month.",
        noMonthlyTasteData: "No monthly taste data yet.",
        topActorsTitle: "Top Actors",
        topActorsSubtitle: "The faces that keep showing up in your watches.",
        noActorPatterns: "No actor patterns yet.",
        noMaleActors: "No male actors yet.",
        noFemaleActors: "No female actors yet.",
        ratedRange: "Rated {{min}}-{{max}}",
        personaCardTitle: "Your Persona Card",
        personaCardSubtitle: "A personality card based on your viewing habits.",
        personaLocked: "Persona Locked",
        watchMoreToReveal: "Watch {{count}} more {{label}} to reveal your viewer identity.",
        personaMale: "Male",
        personaFemale: "Female",
        myPersonaCard: "My persona card",
        shareYourPersona: "Share Your Persona",
      },
    },
  },
  tr: {
    translation: {
      nav: { discover: "Keşfet", movies: "Filmler", series: "Diziler", stats: "İstatistikler", profile: "Profil" },
      common: {
        movie: "Film", movies: "Filmler", series: "Diziler", all: "Tümü", male: "Erkek", female: "Kadın", watchNow: "Şimdi izle", watchedOn: "{{date}} tarihinde izlendi", readMore: "Devamını oku", readLess: "Daha az göster", seeAll: "Tümünü gör", retry: "Tekrar dene", cancel: "İptal", save: "Kaydet", update: "Güncelle", remove: "Kaldır", confirm: "Onayla", goBack: "Geri dön", edit: "Düzenle", searching: "Aranıyor...", loading: "Yükleniyor...", noImage: "Görsel yok", noStill: "Kare yok", noPoster: "Yakında", soon: "Yakında", unknown: "Bilinmiyor", unknownYear: "Bilinmeyen yıl", today: "Bugün", yesterday: "Dün", oneWeekAgo: "1 hafta önce", justWatched: "Sadece izlendi",
      },
      loaders: { syncingData: "StreamBox verilerin senkronize ediliyor", preparingCinemaRoom: "Senin için sinema odası hazırlanıyor", loadingReels: "İçerik yükleniyor", loadingMovies: "Filmler yükleniyor", loadingSeries: "Diziler yükleniyor", loadingMovieDetail: "Detay yükleniyor", loadingSeriesDetail: "Dizi yükleniyor", loadingJourneys: "Yolculuklar yükleniyor", loadingProfile: "Profil yükleniyor..." },
      player: { didYouKnow: "Bunu biliyor muydun?" },
      liveOps: {
        gotIt: "Tamam",
        learnMore: "Daha fazla",
        updateEyebrow: "Güncelleme hazır",
        updateTitle: "Daha iyi bir StreamBox hazır",
        updateBody: "Son iyileştirmeleri arka planda indirdik. Hemen kullanmak için şimdi yeniden başlatabilir ya da izlemeye devam edip bir sonraki açılışta uygulanmasına izin verebilirsin.",
        updateLater: "Sonra",
        updateRestartNow: "Şimdi yeniden başlat",
      },
      startupError: {
        title: "StreamBox hızlı bir yenileme istiyor",
        message: "Kitaplığın açılırken beklenmeyen bir sorun oluştu. Bir kez tekrar dene veya oturumu kapatıp temiz bir giriş yap.",
      },
      welcome: { topTitle: "Hoş geldin", headline: "Filmleri ve dizileri izle.", headlineAccent: "Hepsi tek uygulamada.", description: "Kişiselleştirilmiş öneriler ve ayrıntılı bilgilerle binlerce film ve diziyi keşfet, izle ve takip et.", cta: "Başlayalım" },
      auth: {
        welcomeBack: "Tekrar hoş geldin", createAccount: "Hesabını oluştur", signIn: "Giriş yap", signUp: "Kayıt ol", continueWithGoogle: "Google ile devam et", orContinueWithGoogle: "veya Google ile devam et", createAccountButton: "Hesap oluştur", name: "Ad", email: "E-posta", password: "Şifre", confirmPassword: "Şifreyi doğrula", yourName: "Adın", emailPlaceholder: "you@example.com", enterPassword: "Şifreni gir", reenterPassword: "Şifreni tekrar gir", forgotPassword: "Şifreni mi unuttun?", resetPasswordTitle: "Şifreyi sıfırla", resetPasswordDescription: "E-posta adresini gir, şifreni sıfırlaman için sana 6 haneli bir kod gönderelim.", sendResetCode: "Sıfırlama kodu gönder", rememberPassword: "Şifreni hatırlıyor musun?", verifyEmailTitle: "E-postanı doğrula", verifyEmailDescription: "6 haneli kod şu adrese gönderildi:", verifyContinue: "Doğrula ve devam et", didNotReceiveCode: "Kodu alamadın mı?", checkSpamFolder: "Spam klasörünü kontrol et", setNewPassword: "Yeni şifre belirle", setNewPasswordDescription: "{{email}} adresine gönderilen kodu gir ve yeni şifreni oluştur.", resetCode: "Sıfırlama kodu", resetCodePlaceholder: "6 haneli kod", newPassword: "Yeni şifre", newPasswordPlaceholder: "Yeni şifre", confirmNewPassword: "Yeni şifreyi doğrula", reenterNewPassword: "Yeni şifreyi tekrar gir", passwordChanged: "Şifre değiştirildi", passwordChangedDescription: "Şifren başarıyla güncellendi. Artık yeni şifrenle giriş yapabilirsin.", backToSignIn: "Girişe dön", nameRequired: "Ad gerekli", emailRequired: "E-posta gerekli", invalidEmail: "Geçerli bir e-posta adresi gir", passwordRequired: "Şifre gerekli", passwordRequirements: "Şifre gereksinimleri karşılamıyor", passwordsDoNotMatch: "Şifreler eşleşmiyor", invalidCredentials: "E-posta veya şifre hatalı", somethingWentWrong: "Bir şeyler ters gitti", sendResetFailed: "Sıfırlama kodu gönderilemedi", enterFullOtp: "6 haneli kodu eksiksiz gir", verificationFailed: "Doğrulama başarısız oldu", wrongVerificationCode: "Doğrulama kodu yanlış. Lütfen kontrol edip tekrar dene.", resetFailed: "Sıfırlama başarısız oldu", codeExpired: "Kodun süresi doldu. Yeni kod iste.", invalidCode: "Kod geçersiz", emailRateLimited: "Kısa süre içinde çok fazla e-posta isteği gönderildi. Yaklaşık bir dakika bekleyip tekrar dene.", ruleMinLength: "8+ karakter", ruleLowercase: "Küçük harf", ruleUppercase: "Büyük harf", ruleDigit: "Rakam", ruleSpecial: "Özel karakter",
      },
      home: { discover: "Keşfet", trendingMovies: "Trend filmler", trendingSeries: "Trend diziler", cinematicJourneys: "Sinematik yolculuklar" },
      movies: { movieOfDay: "Günün filmi", noMovieOfDay: "Bugünün filmi yok", topNewMovies: "En iyi yeni filmler", imdbTop250: "IMDb En İyi 250" },
      series: { seriesOfDay: "Günün dizisi", noSeriesOfDay: "Bugünün dizisi yok", topNewSeries: "En iyi yeni diziler", imdbTop250Series: "IMDb En İyi 250 Dizi" },
      search: { placeholder: "Film ve dizi ara...", noResultsForQuery: "\"{{query}}\" için sonuç bulunamadı", tryDifferentKeywords: "Farklı anahtar kelimeler dene ya da yazımı kontrol et", pressEnterForFullResults: "Tam sonuçlar için Enter'a bas", typeAtLeastTwoChars: "Arama için en az 2 karakter yaz", filteredResults: "Filtrelenmiş sonuçlar", resultsCount_one: "{{count}} sonuç", resultsCount_other: "{{count}} sonuç", noResultsFound: "Sonuç bulunamadı", couldNotFindMatch: "Şuna uygun bir sonuç bulamadık:", yourFilters: "filtrelerin", suggestionCheckSpelling: "Yazımı kontrol et ya da farklı anahtar kelimeler dene", suggestionUseShorterTerms: "Daha kısa ya da daha genel terimler kullan", suggestionAdjustFilters: "Filtreleri değiştirmeyi dene", resultsFor: "\"{{query}}\" için sonuçlar", foundMatchingTitles: "Aramana uyan {{count}}+ içerik bulundu" },
      filters: { title: "Filtreler", reset: "Sıfırla", type: "Tür", movies: "Filmler", tvSeries: "TV dizileri", genres: "Türler", releaseYear: "Yayın yılı", from: "Başlangıç", to: "Bitiş", minimumRating: "Minimum puan", sortBy: "Sırala", mostPopular: "En popüler", highestRated: "En yüksek puanlı", newestFirst: "En yeni önce", mostVoted: "En çok oy alan", apply: "Filtreleri uygula" },
      discover: { loadingCollection: "Koleksiyon yükleniyor", noTitlesFound: "İçerik bulunamadı.", loadMore: "Daha fazla yükle", unableToLoadList: "Bu liste yüklenemedi.", unableToLoadMoreTitles: "Daha fazla içerik yüklenemedi." },
      franchise: { title: "Sinematik yolculuklar", subtitle: "Seri evrenlerini doğru sırayla izle", emptyTitle: "Henüz yolculuk yok", emptyDescription: "Seri yol haritaları koleksiyona eklendiğinde burada görünecek.", noEntries: "Bu seri için giriş bulunamadı.", loadingTimeline: "Zaman çizelgesi yükleniyor", titleCount_one: "{{count}} yapım", titleCount_other: "{{count}} yapım", titlesInJourney_one: "Yolculukta {{count}} yapım var", titlesInJourney_other: "Yolculukta {{count}} yapım var", progressCompleted: "{{watched}} / {{total}} tamamlandı", progressCompletedSubtitleDone: "Bu seriyi tamamen bitirdin", progressCompletedSubtitleHint: "İzlendi olarak işaretlemek için herhangi bir yapıma uzun bas", nextUp: "Sıradaki:", journeyComplete: "Yolculuk tamamlandı", endOfTimeline: "Zaman çizelgesinin sonu", completeSagaMessage: "Bu sagadaki tüm {{count}} yapımı deneyimledin. Ne yolculuktu.", epicJourneyMessage: "{{count}} yapım. Tek bir epik yolculuk. Bakalım nereye kadar gideceksin?", signInToTrackProgress: "İlerlemeni takip etmek için giriş yap", markedWatched: "\"{{title}}\" izlendi olarak işaretlendi", unmarkedWatched: "\"{{title}}\" işareti kaldırıldı", failedToUpdateProgress: "İlerleme güncellenemedi" },
      detail: { synopsis: "Özet", castCrew: "Oyuncular ve ekip", similarMovies: "Benzer filmler", similarSeries: "Benzer diziler", seasonsEpisodes: "Sezonlar ve bölümler", seasonsCount_one: "{{count}} sezon", seasonsCount_other: "{{count}} sezon", episodesCount_one: "{{count}} bölüm", episodesCount_other: "{{count}} bölüm", seasonLabel: "{{number}}. sezon", watchEpisode: "İzle S{{season}} B{{episode}}", watchedEpisodesProgress: "{{watched}} / {{total}} bölüm izlendi", episodeSwipeHint: "İzlendi olarak işaretlemek için herhangi bir bölüm kartını sağa kaydır.", noEpisodesForSeason: "Bu sezon için bölüm bulunmuyor.", noSynopsisAvailable: "Özet mevcut değil.", noDetailDataAvailable: "Detay verisi bulunamadı.", unknownReleaseDate: "Yayın tarihi bilinmiyor", cast: "Oyuncular", crew: "Ekip", lowQualityAvailable: "Düşük kalite mevcut", watchAnyway: "Yine de izle", chooseWatchedDateDescription: "Bu {{mediaLabel}} içeriğini gerçekten izlediğin tarihi seç. StreamBox bu tarihi izleme etkinliği, listeler ve istatistikler için kullanır.", markWatchedWithoutDateDescription: "Tam tarihi hatırlamıyorsan bu yapımı tarih eklemeden izlendi olarak işaretleyebilirsin.", markWatchedWithoutDate: "İzlendi olarak işaretle", pickSpecificDate: "Tarih seç", chosenDate: "Seçilen tarih", watchedWithoutDate: "İzlendi olarak işaretlendi", watchedInMonth: "{{date}} içinde izlendi", seasonTrackingDescription: "Bitirdiğin her sezonu bir ay ile takip et veya tarih vermeden sadece izlendi olarak işaretle.", notWatched: "İzlenmedi", monthYearMode: "Ay ve yıl", noDateMode: "Tarih yok", selectMonthYear: "Ay ve yıl seç", seasonsMarkedWatched_one: "{{count}} sezon izlendi olarak işaretlendi", seasonsMarkedWatched_other: "{{count}} sezon izlendi olarak işaretlendi" },
      actor: { loadingProfile: "Profil yükleniyor", unableToLoadProfile: "Oyuncu profili yüklenemedi.", noActorDataAvailable: "Oyuncu verisi bulunamadı.", biography: "Biyografi", biographyFallback: "Bu oyuncu için biyografi bilgisi henüz mevcut değil. Bu profil sonraki aşamada genişletilecek.", knownFor: "Bilinen yapımlar" },
      profile: { watched: "İzlendi", watchlist: "İzleme listesi", liked: "Beğenilen", bioLabel: "Biyografi", locationLabel: "Konum", birthdayLabel: "Doğum tarihi", sectionCount: "{{count}} {{label}}", noMoviesWatchedYet: "Henüz izlenmiş film yok", noSeriesWatchedYet: "Henüz izlenmiş dizi yok", noMoviesInWatchlist: "İzleme listesinde film yok", noSeriesInWatchlist: "İzleme listesinde dizi yok", noMoviesLikedYet: "Henüz beğenilen film yok", noSeriesLikedYet: "Henüz beğenilen dizi yok", filterButton: "Filtrele", filterSheetTitle: "Bu bölümü özelleştir", filterWatchedDescription: "Profil sayfasından çıkmadan izlediklerini sırala veya daralt.", filterWatchlistDescription: "İzleme listesini şu anki ihtiyacına göre şekillendir.", filterLikedDescription: "Beğenilen yapımları puan, yıl veya türe göre odakla.", sortBy: "Sıralama", sortRecentlyAdded: "Yeni eklenenler", sortHighestRated: "En yüksek puan", sortNewestYear: "En yeni yıl", sortTitleAZ: "Başlık A-Z", genreFilterTitle: "Tür", allGenres: "Tüm türler", noGenreFiltersAvailable: "Bu bölümde tür verisi olan yapımlar göründüğünde filtreler burada belirecek.", resetFilters: "Sıfırla", applyFilters: "Uygula", joinedOn: "{{date}} tarihinde katıldı", bornOn: "{{date}} tarihinde doğdu", editProfile: "Profili düzenle", yourName: "Adın", addBio: "Biyografi ekle", addLocation: "Konumunu ekle", searchingLocations: "Konumlar aranıyor...", birthdayPlaceholder: "GG/AA/YYYY", permissionNeeded: "İzin gerekli", allowPhotoAccessProfile: "Profil fotoğrafı ayarlamak için fotoğraf galerisine izin ver.", allowPhotoAccessBanner: "Banner görseli ayarlamak için fotoğraf galerisine izin ver.", imageError: "Görsel hatası", couldNotSaveProfileImage: "StreamBox bu profil görselini kaydedemedi.", couldNotSaveBannerImage: "StreamBox bu banner görselini kaydedemedi." },
      settings: { title: "Ayarlar", pageEyebrow: "Kişisel alan", pageLeadTitle: "StreamBox'ı izleme ritmine göre şekillendir.", pageLeadDescription: "Dil, görünüm, yedekler ve geri bildirim tek bir sakin kontrol alanında burada.", languageTitle: "Dil", languageDescription: "Uygulama dilini seç. Varsayılan dil İngilizcedir ve tercihin hesabına kaydedilir.", appThemeTitle: "Uygulama teması", appThemeDescription: "Sekmeleri, düğmeleri, anahtarları, yükleyicileri ve genel görünümü yöneten vurgu rengini seç.", backupTitle: "Yedekleme ve aktarma", backupDescription: "Bir StreamBox yedek dosyası dışa aktar, başka telefona taşı ve profilini, temanı, beğenilerini, listelerini ve geçmişini geri yüklemek için içe aktar.", dataPortability: "Veri taşınabilirliği", exportAllData: "Tüm verileri dışa aktar", importBackup: "Yedeği içe aktar", preparingBackup: "Yedek hazırlanıyor...", importingBackup: "Yedek içe aktarılıyor...", importReplacesData: "İçe aktarma işlemi bu telefondaki mevcut verileri seçilen yedekle değiştirecek.", backupReady: "yedek dosyası kaydetmeye veya yeni telefonuna göndermeye hazır", backupImported: "yedek içe aktarıldı ve kayıtlı tüm veriler geri yüklendi", exportFailed: "Dışa aktarma başarısız oldu", backupCreateFailed: "StreamBox yedek dosyası oluşturamadı.", importFailed: "İçe aktarma başarısız oldu", backupRestoreFailed: "StreamBox bu yedek dosyasını geri yükleyemedi.", importBackupTitle: "Yedeği içe aktar", importBackupMessage: "Bu işlem, bu telefondaki mevcut StreamBox verilerini seçilen yedekle değiştirecek.", importComplete: "İçe aktarma tamamlandı", importCompleteMessage: "StreamBox verilerin ve ayarların bu telefonda geri yüklendi.", sharingUnavailable: "Bu cihazda paylaşım kullanılamıyor.", feedbackTitle: "Geri bildirim", feedbackDescription: "Bir sorun fark ettiysen ya da bir fikrin varsa, bunu StreamBox içinden doğrudan gönderebilirsin.", feedbackLabel: "Mesajın", feedbackPlaceholder: "Ne olduğunu, ne beklediğini veya neyin iyileştirilebileceğini yaz...", sendFeedback: "Geri bildirim gönder", sendingFeedback: "Geri bildirim gönderiliyor...", feedbackSentTitle: "Geri bildirim gönderildi", feedbackSentMessage: "Teşekkürler. Geri bildirimin başarıyla gönderildi.", feedbackFailedTitle: "Geri bildirim gönderilemedi", feedbackFailedMessage: "StreamBox şu anda geri bildirimini gönderemedi. Lütfen tekrar dene.", feedbackTooShortTitle: "Biraz daha detay gerekli", feedbackTooShortMessage: "Sorunu anlayabilmemiz için lütfen en az kısa bir cümle yaz.", accountTitle: "Hesap", accountDescription: "Bu cihazda StreamBox hesabından çıkış yap.", signOut: "Çıkış yap", signingOut: "Çıkış yapılıyor...", signOutConfirmTitle: "StreamBox'tan çıkış yapılsın mı?", signOutConfirmMessage: "Çıkış yapmak istediğine emin misin? Oturumun sonlandırılacak.", enLabel: "English", enDescription: "Varsayılan uygulama dili.", trLabel: "Türkçe", trDescription: "Doğal Türkçe arayüz.", themeCinemaEmberName: "Cinema Ember", themeCinemaEmberDescription: "Premium sinema ışıltısına sahip klasik StreamBox sıcaklığı.", themeVelvetCrimsonName: "Netflix Kırmızısı", themeVelvetCrimsonDescription: "Cesur ama tanıdık premium yayın görünümü için Netflix esintili kırmızı.", themeAuroraCyanName: "Prime Video Mavisi", themeAuroraCyanDescription: "Parlak yayın vurgusu ve tanıdık koyu mod kontrastıyla Prime Video esintili mavi.", themeEmeraldNoirName: "Emerald Noir", themeEmeraldNoirDescription: "Koyu ekran, zengin yeşil vurgular, sade ve premium görünüm." },
      stats: { emptyState: "İstatistiklerini açmak için izlemeye başla.", recap: "Özet", watched: "İzlendi", hours: "Saat", episodes: "Bölüm", avgScore: "Ort. puan", watchActivityTitle: "İzleme etkinliği", watchActivitySubtitle: "Hafta hafta ne sıklıkla izlediğini gösterir.", chartTotal: "Toplam", chartPeakWeek: "Zirve hafta", chartActive: "Aktif", now: "Şimdi", weekShort: "h", decadeSpreadTitle: "Dönem dağılımı", decadeSpreadSubtitle: "Seçimlerinin hangi dönemlerden geldiğini gösterir.", noDecadeDistribution: "Henüz dönem dağılımı yok.", genreBreakdownTitle: "Tür dağılımı", genreBreakdownSubtitle: "En çok izlediğin türler sayıya göre sıralanır.", noGenrePatterns: "Henüz tür örüntüsü yok.", genreRadarTitle: "Tür radarı", genreRadarSubtitle: "Favori türlerinin birbirine göre dağılımını görsel olarak gösterir.", dominant: "Baskın", share: "Pay", ratingDistributionTitle: "Puan dağılımı", ratingDistributionSubtitle: "Verdiğin puanların ölçeğe nasıl yayıldığını gösterir.", runtimeExtremesTitle: "Süre uçları", runtimeExtremesSubtitle: "En kısa ve en uzun izlediklerin yan yana.", longest: "En uzun", shortest: "En kısa", tasteEvolutionTitle: "Zevk gelişimi", tasteEvolutionSubtitle: "Tür tercihlerinin aydan aya nasıl değiştiğini gösterir.", noMonthlyTasteData: "Henüz aylık zevk verisi yok.", topActorsTitle: "En çok izlenen oyuncular", topActorsSubtitle: "İzlediklerinde sürekli karşına çıkan yüzler.", noActorPatterns: "Henüz oyuncu örüntüsü yok.", noMaleActors: "Henüz erkek oyuncu yok.", noFemaleActors: "Henüz kadın oyuncu yok.", ratedRange: "{{min}}-{{max}} arası puanlananlar", personaCardTitle: "Persona kartın", personaCardSubtitle: "İzleme alışkanlıklarına göre oluşturulmuş kişilik kartı.", personaLocked: "Persona kilitli", watchMoreToReveal: "İzleyici kimliğini açmak için {{count}} {{label}} daha izle.", personaMale: "Erkek", personaFemale: "Kadın", myPersonaCard: "Persona kartım", shareYourPersona: "Personanı paylaş" },
    },
  },
} as const;

export type TranslationResources = typeof resources;
