insert into public.app_announcements (
  slug,
  priority,
  is_active,
  requires_auth,
  display_version,
  title_en,
  title_tr,
  body_en,
  body_tr,
  eyebrow_en,
  eyebrow_tr,
  cta_label_en,
  cta_label_tr,
  cta_url,
  image_url,
  accent_hex,
  starts_at,
  platforms
)
values (
  'streambox-new-apk-download-2026-06',
  2500,
  true,
  false,
  1,
  'New StreamBox APK Available',
  'Yeni StreamBox APK hazir',
  'A new version is ready with the updated logo, better playback controls, improved ad blocking, faster loading, and a more polished design. Download the latest APK from streamboxapp.stream.',
  'Yeni logo, daha iyi oynatma kontrolleri, gelismis reklam engelleme, daha hizli yukleme ve daha temiz tasarim iceren yeni surum hazir. En yeni APK dosyasini streamboxapp.stream uzerinden indirin.',
  'Update available',
  'Guncelleme hazir',
  'Download APK',
  'APK indir',
  'https://streamboxapp.stream',
  'announcements/new-apk-logo-banner.png',
  '#22C55E',
  timezone('utc', now()),
  array['android']::text[]
)
on conflict (slug) do update
  set priority = excluded.priority,
      is_active = excluded.is_active,
      requires_auth = excluded.requires_auth,
      display_version = public.app_announcements.display_version + 1,
      title_en = excluded.title_en,
      title_tr = excluded.title_tr,
      body_en = excluded.body_en,
      body_tr = excluded.body_tr,
      eyebrow_en = excluded.eyebrow_en,
      eyebrow_tr = excluded.eyebrow_tr,
      cta_label_en = excluded.cta_label_en,
      cta_label_tr = excluded.cta_label_tr,
      cta_url = excluded.cta_url,
      image_url = excluded.image_url,
      accent_hex = excluded.accent_hex,
      starts_at = excluded.starts_at,
      platforms = excluded.platforms,
      updated_at = timezone('utc', now());
