create extension if not exists pg_cron;
create extension if not exists pg_net;

alter table public.external_ratings_cache
  add column if not exists access_count bigint not null default 0,
  add column if not exists refresh_count bigint not null default 0,
  add column if not exists last_status text not null default 'cold',
  add column if not exists last_refreshed_by text,
  add column if not exists release_year integer;

update public.external_ratings_cache
set refresh_count = greatest(coalesce(refresh_count, 0), 1)
where fetched_at is not null;

update public.external_ratings_cache
set last_status = 'negative'
where coalesce(imdb_rating, rotten_tomatoes, metacritic) is null;

update public.external_ratings_cache
set release_year = nullif(substring(raw_payload ->> 'Year' from '\d{4}'), '')::integer
where release_year is null
  and raw_payload ? 'Year';

create index if not exists external_ratings_cache_last_accessed_at_idx
  on public.external_ratings_cache (last_accessed_at desc);

create index if not exists external_ratings_cache_hot_refresh_idx
  on public.external_ratings_cache (last_status, expires_at, last_accessed_at desc, access_count desc);

create table if not exists public.external_ratings_function_logs (
  id bigint generated by default as identity primary key,
  function_name text not null,
  event_type text not null,
  status_code integer not null,
  imdb_id text,
  cache_source text,
  latency_ms integer,
  error_message text,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists external_ratings_function_logs_created_at_idx
  on public.external_ratings_function_logs (created_at desc);

create index if not exists external_ratings_function_logs_status_idx
  on public.external_ratings_function_logs (status_code, created_at desc);

create index if not exists external_ratings_function_logs_event_type_idx
  on public.external_ratings_function_logs (event_type, created_at desc);

create table if not exists public.external_ratings_alert_events (
  id bigint generated by default as identity primary key,
  alert_code text not null,
  severity text not null,
  message text not null,
  metric_value numeric,
  snapshot jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists external_ratings_alert_events_created_at_idx
  on public.external_ratings_alert_events (created_at desc);

alter table public.external_ratings_function_logs enable row level security;
alter table public.external_ratings_alert_events enable row level security;

revoke all on public.external_ratings_function_logs from anon;
revoke all on public.external_ratings_function_logs from authenticated;
revoke all on public.external_ratings_alert_events from anon;
revoke all on public.external_ratings_alert_events from authenticated;

create or replace function public.get_hot_external_ratings_candidates(batch_size integer default 25)
returns table (imdb_id text)
language sql
security definer
set search_path = public
as $$
  select cache.imdb_id
  from public.external_ratings_cache as cache
  where cache.last_accessed_at >= timezone('utc', now()) - interval '30 days'
    and cache.last_status in ('warm', 'hot')
    and cache.expires_at <= timezone('utc', now()) + interval '2 days'
  order by
    case cache.last_status when 'hot' then 0 when 'warm' then 1 else 2 end,
    case when cache.expires_at <= timezone('utc', now()) then 0 else 1 end,
    cache.access_count desc,
    cache.last_accessed_at desc
  limit greatest(batch_size, 1);
$$;

revoke all on function public.get_hot_external_ratings_candidates(integer) from anon;
revoke all on function public.get_hot_external_ratings_candidates(integer) from authenticated;

create or replace view public.external_ratings_active_alerts as
with
recent_15m as (
  select *
  from public.external_ratings_function_logs
  where created_at >= timezone('utc', now()) - interval '15 minutes'
),
recent_60m as (
  select *
  from public.external_ratings_function_logs
  where created_at >= timezone('utc', now()) - interval '60 minutes'
)
select
  'high_error_rate'::text as alert_code,
  'high'::text as severity,
  format('%s server-side ratings errors in the last 15 minutes.', count(*)) as message,
  count(*)::numeric as metric_value,
  timezone('utc', now()) - interval '15 minutes' as window_start,
  timezone('utc', now()) as evaluated_at
from recent_15m
where status_code >= 500
having count(*) >= 3
union all
select
  'stale_cache_burst'::text as alert_code,
  'medium'::text as severity,
  format('%s stale-cache responses served in the last hour.', count(*)) as message,
  count(*)::numeric as metric_value,
  timezone('utc', now()) - interval '60 minutes' as window_start,
  timezone('utc', now()) as evaluated_at
from recent_60m
where event_type = 'stale_cache_served'
having count(*) >= 5
union all
select
  'slow_upstream'::text as alert_code,
  'medium'::text as severity,
  format('Average ratings latency is %s ms across %s requests in the last 15 minutes.', round(avg(latency_ms))::integer, count(*)) as message,
  round(avg(latency_ms), 2) as metric_value,
  timezone('utc', now()) - interval '15 minutes' as window_start,
  timezone('utc', now()) as evaluated_at
from recent_15m
where latency_ms is not null
having count(*) >= 10 and avg(latency_ms) >= 2500;

create or replace function public.capture_external_ratings_alerts()
returns integer
language plpgsql
security definer
set search_path = public
as $alerts$
declare
  inserted_count integer := 0;
begin
  insert into public.external_ratings_alert_events (alert_code, severity, message, metric_value, snapshot)
  select
    alert_code,
    severity,
    message,
    metric_value,
    jsonb_build_object(
      'window_start', window_start,
      'evaluated_at', evaluated_at
    )
  from public.external_ratings_active_alerts as alerts
  where not exists (
    select 1
    from public.external_ratings_alert_events as existing
    where existing.alert_code = alerts.alert_code
      and existing.created_at >= timezone('utc', now()) - interval '15 minutes'
  );

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$alerts$;

revoke all on function public.capture_external_ratings_alerts() from anon;
revoke all on function public.capture_external_ratings_alerts() from authenticated;

create or replace function public.cleanup_external_ratings_monitoring(retention_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $cleanup$
declare
  deleted_logs integer := 0;
  deleted_alerts integer := 0;
begin
  delete from public.external_ratings_function_logs
  where created_at < timezone('utc', now()) - make_interval(days => greatest(retention_days, 1));
  get diagnostics deleted_logs = row_count;

  delete from public.external_ratings_alert_events
  where created_at < timezone('utc', now()) - make_interval(days => greatest(retention_days, 1));
  get diagnostics deleted_alerts = row_count;

  return jsonb_build_object(
    'deleted_log_rows', deleted_logs,
    'deleted_alert_rows', deleted_alerts,
    'retention_days', greatest(retention_days, 1)
  );
end;
$cleanup$;

revoke all on function public.cleanup_external_ratings_monitoring(integer) from anon;
revoke all on function public.cleanup_external_ratings_monitoring(integer) from authenticated;

create or replace function public.ensure_external_ratings_jobs(
  project_url text,
  anon_key text,
  refresh_function_name text default 'refresh-hot-ratings',
  refresh_cron text default '17 */6 * * *',
  alert_cron text default '*/15 * * * *',
  cleanup_cron text default '33 3 * * *'
)
returns void
language plpgsql
security definer
set search_path = public
as $jobs$
begin
  if coalesce(trim(project_url), '') = '' then
    raise notice 'project_url is required.';
    return;
  end if;

  if coalesce(trim(anon_key), '') = '' then
    raise notice 'anon_key is required.';
    return;
  end if;

  if not exists (
    select 1 from cron.job where jobname = 'external-ratings-hot-refresh'
  ) then
    perform cron.schedule(
      'external-ratings-hot-refresh',
      refresh_cron,
      format(
        $job$
          select net.http_post(
            url := %L || '/functions/v1/' || %L,
            headers := jsonb_build_object(
              'Content-Type', 'application/json',
              'apikey', %L,
              'Authorization', 'Bearer ' || %L
            ),
            body := %L::jsonb
          );
        $job$,
        project_url,
        refresh_function_name,
        anon_key,
        anon_key,
        '{"batchSize":25}'
      )
    );
  end if;

  if not exists (
    select 1 from cron.job where jobname = 'external-ratings-alert-capture'
  ) then
    perform cron.schedule(
      'external-ratings-alert-capture',
      alert_cron,
      $cron$select public.capture_external_ratings_alerts();$cron$
    );
  end if;

  if not exists (
    select 1 from cron.job where jobname = 'external-ratings-monitoring-cleanup'
  ) then
    perform cron.schedule(
      'external-ratings-monitoring-cleanup',
      cleanup_cron,
      $cron$select public.cleanup_external_ratings_monitoring(30);$cron$
    );
  end if;
end;
$jobs$;

revoke all on function public.ensure_external_ratings_jobs(text, text, text, text, text, text) from anon;
revoke all on function public.ensure_external_ratings_jobs(text, text, text, text, text, text) from authenticated;

-- After this migration runs, install the scheduled jobs with:
-- select public.ensure_external_ratings_jobs(
--   'https://zbeexmqmcwtlsbbuuqor.supabase.co',
--   '<your_supabase_anon_key>',
--   'refresh-hot-ratings'
-- );
